Apply pipeline changes and suggestions

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -60,7 +60,7 @@ stages:
 
     variables:  
       ANDROID_EMU_NAME: test
-      ANDROID_SDK_ID: system-images;android-28;google_apis_playstore;x86
+      ANDROID_SDK_ID: system-images;android-30;google_apis_playstore;x86_64
 
     steps:
     - task: CmdLine@2
@@ -85,12 +85,19 @@ stages:
           echo "Starting emulator"
           nohup $ANDROID_HOME/emulator/emulator -avd "$(ANDROID_EMU_NAME)" -gpu swiftshader_indirect -noaudio -no-boot-anim -no-snapshot -verbose > /dev/null 2>&1 &
           $ANDROID_HOME/platform-tools/adb wait-for-device
-          while [[ $? -ne 0 ]]; do sleep 1; $ANDROID_HOME/platform-tools/adb shell pm list packages; done;
+          for i in {1..300}; do
+            $ANDROID_HOME/platform-tools/adb shell pm list packages >/dev/null 2>&1 && break
+            sleep 2
+          done
+          if [[ $i -eq 60 ]]; then
+            echo "Emulator failed to boot in time" >&2
+            exit 1
+          fi
           $ANDROID_HOME/platform-tools/adb devices
           echo "Emulator started"
 
           echo "Installing Appium"
-          npm install -g appium@latest
+          npm install -g appium@2
           ln -fs /usr/local/lib/node_modules/appium/build/lib/main.js /usr/local/bin/appium
           chmod +x /usr/local/bin/appium
           export PATH=$PATH:/usr/local/bin/appium
@@ -110,16 +117,6 @@ stages:
           export PATH=$PATH:/usr/local/bin/appium-doctor
           appium-doctor
           echo "Appium doctor installed and executed"
-
-          
-          echo "Updating Chrome on Emulator"
-          # Download Chrome APK (you might want to specify a different version or method based on your needs)
-          wget https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=9799753&key=f031adeb710376d4956dfa4e30a00ad603d690e5&forcebaseapk=true -O /tmp/chrome.apk          
-          # Install Chrome APK on the emulator
-          $ANDROID_HOME/platform-tools/adb install -r /tmp/chrome.apk
-          # Verify the installation
-          $ANDROID_HOME/platform-tools/adb shell pm list packages | grep com.android.chrome
-          echo "Chrome installed/updated"
 
     - task: CmdLine@2
       displayName: 'Start Appium server'
